### ISSUE TITLE
Specify HWND

### ISSUE THREAD

**Issue by leaanthony** [harry1453/go-common-file-dialog#3]
Firstly, thanks for a superb project!
I've noticed that as the HWND isn't specified, it can sometime appear beneath my application window. How easy would it be to add a method to set the parent HWND? Perhaps as a property on `cfd.DialogConfig`? Cheers.

**Comment by harry1453** [comment]
Hey!

That's strange because I've never had that issue, not that I don't believe that you're having it.

Please could let me know if this branch works for you? https://github.com/harry1453/go-common-file-dialog/tree/specify-hwnd

**Comment by leaanthony** [comment]
Amazing turn around! Thanks for this. Will check in the morning and let you know. I'm looking to integrate you project as part of https://github.com/wailsapp/wails so I hope to provide more exposure to your amazing project 👍

**Comment by leaanthony** [comment]
Works brilliantly. Thanks!

**Comment by leaanthony** [comment]
I've made a temporary fork with the patch. Let me know when you tag the release and I'll update my go.mod. Awesome job!

**Comment by harry1453** [comment]
Hi @leaanthony! Back now, will get around to replying to your email soon, sorry for the delay. Glad it works well!

**Comment by harry1453** [comment]
New tag/release made.
