### ISSUE TITLE
Cancelled flag

### ISSUE THREAD

**Issue by leaanthony** [harry1453/go-common-file-dialog#4]
Currently, if the user presses cancel or closes a dialog, it returns an error with the text "cancelled by user". It would be great if `Show()` returned a flag indicating if it was cancelled. I realise this would be an API breaking change!

**Comment by harry1453** [comment]
Hm, I'll see how this could be done. Maybe the easiest, non-breaking way would be to return a constant error that can be checked by the caller

**Comment by harry1453** [comment]
Could you check if the latest master works for you?

**Comment by leaanthony** [comment]
Works brilliantly, thanks!
